name: TrAVCA
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11.4
  - pytorch::pytorch=2.4.0
  - pytorch::torchvision=0.19.0
  - pytorch::torchaudio=2.4.0
  - pytorch::pytorch-cuda=11.8
  - ftfy=5.8
  - termcolor=2.1.*
  - lxml=5.2.*
  - pip
  - pip:
      - transformers==4.30.*
      - scikit-learn==1.3.*
      - pandas==2.0.*
      - wandb==0.15.*
      - numpy==1.25.*
      - opencv-python==4.8.0.*
      - jupyterlab==4.2.*
